#!/usr/bin/env python3
"""Generate charmap.inc: ASCII -> Odyssey 2 character-generator GLYPH INDEX.

Vendored from fujinet-firmware/pico/o2/tools/genmap.py and cut down twice over.
That version emits two 96-byte tables of finished VDC character pointers, one
for the low byte and one for the colour plus the 9th bit, for ASCII $20-$7F.

This one emits a single 64-byte table of glyph indices for $20-$5F, and
glyph_ptr does the arithmetic:

    pointer = glyph*8 - Y/2          (9 bits; bit 8 goes in the control byte)

Lowercase folds to uppercase in glyph_ptr rather than costing another 64
entries. 192 bytes become 64, and those 128 bytes are what let the URL literals
move into page $E00 -- which in turn freed the whole of page $D00 for code. On a
3K cart with a poker client in it, that is not a micro-optimisation.

Verified against o2em's cset.c and vdc.c:536 (`c = chr + ypos; if (col&1) c += 256`).
"""
G = {}
for i, ch in enumerate("0123456789"):
    G[ch] = i
G[':'] = 0x0A; G['$'] = 0x0B; G[' '] = 0x0C
# '?' is the wire's hole-card marker and nothing else this client ever draws, so
# it is mapped to the solid block rather than to a question mark: two of them
# side by side on the card row are 16 pixels of solid colour, which reads as the
# back of a card. card_col paints them blue.
G['?'] = 0x2F
G['L'] = 0x0E; G['P'] = 0x0F; G['+'] = 0x10; G['W'] = 0x11; G['E'] = 0x12
G['R'] = 0x13; G['T'] = 0x14; G['U'] = 0x15; G['I'] = 0x16; G['O'] = 0x17
G['Q'] = 0x18; G['S'] = 0x19; G['D'] = 0x1A; G['F'] = 0x1B; G['G'] = 0x1C
G['H'] = 0x1D; G['J'] = 0x1E; G['K'] = 0x1F; G['A'] = 0x20; G['Z'] = 0x21
G['X'] = 0x22; G['C'] = 0x23; G['V'] = 0x24; G['B'] = 0x25; G['M'] = 0x26
G['.'] = 0x27; G['-'] = 0x28; G['x'] = 0x29; G['='] = 0x2B; G['Y'] = 0x2C
G['N'] = 0x2D; G['/'] = 0x2E; G['\\'] = 0x3B
BLANK = 0x0C
YP, COL = 40, 0x0E

# The card row draws raw wire bytes, so every rank and suit character the server
# can send has to have a glyph: 2-9 T J Q K A and s h d c, plus '?' for a hidden
# card. All of them are above; this asserts it rather than trusting the reading.
for ch in "23456789TJQKA" "SHDC" "?":
    assert ch in G, "no glyph for card character %r" % ch

glyphs = [G.get(chr(c), BLANK) for c in range(0x20, 0x60)]

def rows(vals, per=16):
    return "\n".join("    db  " + ",".join("0%02Xh" % v for v in vals[i:i + per])
                     for i in range(0, len(vals), per))

print("""; charmap.inc -- GENERATED by tools/genmap.py, do not edit.
;
; ASCII $20-$5F -> Odyssey 2 character-generator glyph index. Anything the O2
; charset cannot render becomes a blank (glyph $0C). Lowercase is NOT in the
; table: glyph_ptr folds $60-$7F down by $20 first, and turns the index into a
; VDC character pointer with the row's bias. See glyph_ptr in fujilib.inc.
;
; Shares page $E00 with the strings, the sound cues and the URL literals, all
; read through the one MOVP stub -- MOVP reads the page the PC is in.

CMAP_COL equ 0%02Xh              ; colour bits of the character control byte

    org 0E00h
cm_get:                     ; A = offset in page $E00 -> A = byte there
    movp a,@a
    ret

cm_glyph:
%s""" % (COL, rows(glyphs)))
