#!/usr/bin/env bash
# build.sh -- assemble the Astrocade 5 Card Stud client with zmac.
#
# Usage: ./build.sh
#
# Output: build/5card.bin, always exactly 8192 bytes: the assembled code,
# zero-padded, mailbox pages clear, "FUJI" claim signature at 0x1CFC so the
# mailbox stays alive when the image is booted over the network. The layout
# contract is enforced by the firmware tree's checkrom.py; tools/checksize.py
# then prints the per-module budget table.
#
# Environment:
#   ENDPOINT=...        game server (default https://5card.carr-designs.com/)
#   FUJI_FIRMWARE=path  fujinet-firmware checkout (default ~/Workspace/fujinet-firmware)
#
# The toolchain and layout checker are the ones vendored with the cartridge
# bring-up in fujinet-firmware pico/astrocade -- one source of truth for the
# window contract rather than a drifting copy here.

set -euo pipefail
cd "$(dirname "$0")"

WINDOW=8192
CLAIM_OFF=$((0x1CFC))
ROM_TOP=$((0x1B00))

FUJI_FIRMWARE=${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}
PICO="$FUJI_FIRMWARE/pico/astrocade"
if [ ! -d "$PICO" ]; then
    echo "build.sh: $PICO not found; set FUJI_FIRMWARE" >&2
    exit 1
fi

# zmac: PATH first, then the copy vendored with the bring-up (built on
# demand -- see its PROVENANCE.md).
find_zmac() {
    if command -v zmac >/dev/null 2>&1; then
        echo zmac
        return
    fi
    local tree="$PICO/tools/zmac"
    if [ ! -x "$tree/zmac" ]; then
        touch "$tree/zmac.c"    # keep it newer than zmac.y: no yacc wanted
        make -C "$tree" zmac >/dev/null
    fi
    echo "$tree/zmac"
}

ZMAC=$(find_zmac)
mkdir -p build

# The server the game talks to, overridable without editing source:
#   ENDPOINT=http://192.168.1.10:8080/ ./build.sh
# Regenerated every run so a stale value cannot survive an environment change.
ENDPOINT="${ENDPOINT:-https://5card.carr-designs.com/}"
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "$ENDPOINT"
    echo "        DB      0"
} > build/endpoint.inc

# Build flags. DEMO=1 assembles the static mock table instead of the game.
{
    echo "; generated by build.sh -- do not edit"
    echo "DEMO    EQU     ${DEMO:-0}"
} > build/flags.inc

# zmac 1.3 resolves INCLUDE against the cwd; assemble from here.
"$ZMAC" -o build/5card.raw -x build/5card.lst 5card.asm

size=$(wc -c < build/5card.raw)
if [ "$size" -gt "$ROM_TOP" ]; then
    echo "build.sh: 5card is $size bytes, over the $ROM_TOP ROM top" >&2
    exit 1
fi

# Pad to the full window, clear above ROM_TOP, stamp the claim.
{
    cat build/5card.raw
    head -c $((WINDOW - size)) /dev/zero
} > build/5card.bin
printf 'FUJI' | dd of=build/5card.bin bs=1 seek=$CLAIM_OFF \
    conv=notrunc status=none
rm -f build/5card.raw

python3 "$PICO/tools/checkrom.py" build/5card.bin
python3 tools/checksize.py build/5card.lst
