#!/bin/bash
# Assemble the Odyssey 2 cart with Macroassembler AS.
#
#   ./build.sh            # build 5card
#   ./build.sh 5card      # same
#
# AS is not packaged for Arch, and Debian/Ubuntu's "asl"/"asl-*" are the Advanced
# Simulation Library -- something else entirely. A native asl/asw on PATH is
# preferred; otherwise this falls back to the Windows binaries under
# ~/Workspace/o2workspace/bin through wine, which is how o2workspace ships them.
# Both were checked upstream to produce byte-identical images.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
AS_BIN="${AS_BIN:-$HOME/Workspace/o2workspace/bin}"
OUT="${OUT:-$HERE/build}"
mkdir -p "$OUT"

if command -v asl >/dev/null 2>&1; then
  AS=asl; P2BIN=p2bin
elif command -v asw >/dev/null 2>&1; then
  AS=asw; P2BIN=p2bin
else
  AS="wine $AS_BIN/asw.exe"; P2BIN="wine $AS_BIN/p2bin.exe"
  export WINEDEBUG=-all
fi
run_as()    { ( cd "$OUT" && $AS "$@" ); }
run_p2bin() { ( cd "$OUT" && $P2BIN "$@" ); }

# The server the game talks to. Overridable so a local instance can be pointed
# at without editing source:
#   ENDPOINT=http://192.168.1.10:8080/ ./build.sh
ENDPOINT="${ENDPOINT:-https://5card.carr-designs.com/}"

cp "$HERE"/*.a48 "$HERE"/*.inc "$HERE/g7000.h" "$OUT/"
printf '; GENERATED by build.sh, do not edit. Keep the whole URL short: the\n; devicespec length is counted into a single byte (V_ULEN), and the rest of a\n; /state request is about 45 characters on top of this.\nurl_endpoint: db "%s",0\n' \
  "$ENDPOINT" > "$OUT/endpoint.inc"

# Cartridge banks. The FujiNet cart decodes bank = 3 - (P10 + 2*P11), so four
# banks of 3K is the hardware ceiling, and o2em only recognises 2 or 4 of them
# (a 3-bank image is mapped onto the MegaCart romlatch scheme instead --
# o2em/main.c:843-851). Each bank is its own assembly at $400-$FFF: PHASE would
# let one assembly emit all four, but it shifts the listing's address column
# too, and then checklayout.py sees every bank overlapping every other.
BANKS="${BANKS:-4}"

for src in "${@:-5card}"; do
  b=$(basename "$src" .a48)
  parts=""
  for n in $(seq 0 $((BANKS-1))); do
    cat > "$OUT/${b}_b$n.a48" <<EOF
; GENERATED by build.sh, do not edit. One wrapper per cartridge bank: BANK is
; what the P1 constants derive their bank-select bits from (vdctext.inc).
BANK    equ $n
    include "$b.a48"
EOF
    run_as -q -L "${b}_b$n.a48"
    run_p2bin "${b}_b$n.p" "${b}_b$n.bin" -r 0x400-0xFFF -l 0
    # Three failure modes AS and p2bin report either badly or not at all: a
    # routine that grew into the next pinned one ("overlapping memory
    # allocation!", with no location), a cross-bank call that never restores MB,
    # and a P1 write carrying another bank's select bits. None of the last two
    # produce a diagnostic at all -- they assemble clean and jump somewhere else
    # at runtime.
    python3 "$HERE/tools/checklayout.py" "$OUT/${b}_b$n.lst"
    python3 "$HERE/tools/checkmb.py" "$OUT/${b}_b$n.lst"
    python3 "$HERE/tools/checkp1.py" "$OUT/${b}_b$n.lst" "$n"
    # Bank 0 is the boot bank and has to be the LAST chunk of the file, because
    # the select pair is inverted and both bits high at reset picks bank 0
    # (o2map.c:61-71). So the image is assembled back to front.
    parts="$OUT/${b}_b$n.bin $parts"
  done
  # The bytes a bank switch runs through have to be the same in every bank, and
  # the image has to be exactly BANKS x 3K or o2em maps it as something else.
  python3 "$HERE/tools/checkresident.py" "$OUT/$b" "$BANKS"
  cat $parts > "$OUT/$b.bin"
  size=$(wc -c < "$OUT/$b.bin")
  if [ "$size" -ne $((BANKS * 3072)) ]; then
    echo "$b.bin is $size bytes, expected $((BANKS * 3072))" >&2
    exit 1
  fi
done
ls -l "$OUT"/$b.bin
