#!/usr/bin/env python3
"""mkfont.py -- Lynx 4x6 font BMPs -> assets/font.inc (zmac, 1bpp).

The Lynx port's glyphs (src/lynx/4x6/*.bmp, 4x6 4bpp Windows BMPs) are the
family's 4-pixel-wide font, and 4 pixels is exactly one Astrocade screen
byte at 2bpp -- so every glyph row here is one byte, ink in the HIGH nibble
(the magic expander takes the high nibble on the first write after the
MAGIC register is set; bit 7 is the leftmost pixel).

Codepoints 0x20-0x5F, 64 glyphs, 6 bytes each, 384 bytes total. The
file-to-codepoint table is src/lynx/4x6font.s's, transcribed. Output is
committed; rerun after art changes (make assets).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LYNX = os.path.normpath(os.path.join(HERE, "..", "..", "src", "lynx", "4x6"))
OUT = os.path.normpath(os.path.join(HERE, "..", "assets", "font.inc"))

W, H = 4, 6
FIRST, LAST = 0x20, 0x5F

# src/lynx/4x6font.s, 0x20-0x5F (0x26 reuses plus.spr for ampersand there).
NAMES = {
    0x20: "space", 0x21: "exclam", 0x22: "quotation", 0x23: "hash",
    0x24: "dollar", 0x25: "percent", 0x26: "plus", 0x27: "apostr",
    0x28: "left-rbrack", 0x29: "right-rbrack", 0x2A: "asterisk",
    0x2B: "plus", 0x2C: "comma", 0x2D: "hypen", 0x2E: "period",
    0x2F: "forwardslash",
    0x3A: "colon", 0x3B: "semicolon", 0x3C: "left-abrack", 0x3D: "equal",
    0x3E: "right-abrack", 0x3F: "question", 0x40: "at",
    0x5B: "left-sbrack", 0x5C: "backslash", 0x5D: "right-sbrack",
    0x5E: "carat", 0x5F: "underscore",
}
for d in range(10):
    NAMES[0x30 + d] = chr(0x30 + d)
for c in range(26):
    NAMES[0x41 + c] = chr(0x61 + c)


def read_bmp_4x6(path: str) -> list[list[int]]:
    """Rows top-down of 0/1 ink flags from a 4x6 4bpp Windows BMP."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:2] != b"BM":
        raise SystemExit(f"mkfont: {path}: not a BMP")
    offset = int.from_bytes(data[10:14], "little")
    w = int.from_bytes(data[18:22], "little")
    h = int.from_bytes(data[22:26], "little", signed=True)
    bpp = int.from_bytes(data[28:30], "little")
    if (w, h, bpp) != (W, H, 4):
        raise SystemExit(f"mkfont: {path}: {w}x{h}x{bpp}, want {W}x{H}x4")
    stride = ((w * 4 + 31) // 32) * 4
    rows = []
    for y in range(h):                    # BMP rows are bottom-up
        base = offset + (h - 1 - y) * stride
        row = []
        for x in range(w):
            byte = data[base + x // 2]
            nib = byte >> 4 if x % 2 == 0 else byte & 0x0F
            row.append(1 if nib == 0 else 0)    # black ink on white ground
        rows.append(row)
    return rows


def main() -> int:
    lines = [
        "; font.inc -- 4x6 font, 1bpp, GENERATED by tools/mkfont.py from",
        "; src/lynx/4x6/*.bmp -- do not edit; rerun `make assets`.",
        ";",
        "; 64 glyphs, codepoints 20H-5FH, 6 bytes each, top row first.",
        "; Ink is the HIGH nibble, bit 7 leftmost: one magic-expander write",
        "; per row (the expander takes the high nibble first after a MAGIC",
        "; register write -- see gfx.inc).",
        "FONT46:",
    ]
    for cp in range(FIRST, LAST + 1):
        name = NAMES.get(cp)
        if name is None:
            raise SystemExit(f"mkfont: no source file mapped for {cp:#04x}")
        rows = read_bmp_4x6(os.path.join(LYNX, f"{name}.bmp"))
        label = chr(cp) if cp > 0x20 else "space"
        lines.append(f"; {cp:02X}H '{label}'")
        for row in rows:
            val = 0
            for x, ink in enumerate(row):
                if ink:
                    val |= 0x80 >> x
            art = "".join("#" if ink else "." for ink in row)
            lines.append(f"        DB      {val:03X}H    ; {art}")
    lines.append("")

    # Self-checks: glyph count and total size are structural.
    n_glyphs = LAST - FIRST + 1
    n_bytes = sum(1 for l in lines if l.strip().startswith("DB"))
    assert n_glyphs == 64, n_glyphs
    assert n_bytes == n_glyphs * H, n_bytes

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"mkfont: {n_glyphs} glyphs, {n_bytes} bytes -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
