#!/usr/bin/env python3
"""mkudc.py -- generate assets/udc.inc, the two UDC banks for the client.

The 2637 UVI has 8 user-defined characters at $1980-$19BF (codes $38-$3F),
8 bytes each, bit 7 leftmost, and THE FIRST FOUR double as the sprite
images. The client reloads the whole bank on screen changes:

  bank T (title + game):  $38-$3B suits (= suit sprites), $3C "10" rank,
                          $3D chip, $3E card-back lattice, $3F chevron
  bank L (lobby + name):  $38 chevron arrow (= sprite 0 cursor), $39 '/',
                          $3A '-', rest blank

The suit shapes are the Astrocade port's proven 5-wide art
(astrocade/tools/mkcards.py), placed at columns 2-6 to sit on the same
metrics as the built-in font (which inks bits 5-1). Every emitted byte
carries the row's art in the comment so the generated file reviews by eye.

Output is committed; regenerate with `make assets`.
"""

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "udc.inc"

# 8x8 art, '#' = ink. Suit bodies are the astrocade 5-wide shapes at
# columns 2-6, blank top row, matching the built-in font's metrics.
GLYPHS = {
    "HEART": [
        "........",
        "..#.#...",
        ".#####..",
        ".#####..",
        "..###...",
        "...#....",
        "........",
        "........",
    ],
    "DIAMOND": [
        "........",
        "...#....",
        "..###...",
        ".#####..",
        "..###...",
        "...#....",
        "........",
        "........",
    ],
    "CLUB": [
        "........",
        "...#....",
        "..###...",
        ".##.##..",
        ".#####..",
        "...#....",
        "..###...",
        "........",
    ],
    "SPADE": [
        "........",
        "...#....",
        "..###...",
        ".#####..",
        ".#####..",
        "...#....",
        "..###...",
        "........",
    ],
    # "10" in one cell: a 2px '1' and a 4px '0'.
    "TEN": [
        "........",
        ".#..##..",
        "##.#..#.",
        ".#.#..#.",
        ".#.#..#.",
        ".#.#..#.",
        ".#..##..",
        "........",
    ],
    # bet chip: circle with a cross-dot centre
    "CHIP": [
        "........",
        "..###...",
        ".##.##..",
        ".#.#.#..",
        ".##.##..",
        "..###...",
        "........",
        "........",
    ],
    # card back: edge-to-edge diamond lattice (two cells side by side tile)
    "BACK": [
        "#...#...",
        ".#.#.#.#",
        "..#...#.",
        ".#.#.#.#",
        "#...#...",
        ".#.#.#.#",
        "..#...#.",
        ".#.#.#.#",
    ],
    # cursor chevron (fujidisp's $3C art)
    "CHEVR": [
        ".#......",
        ".##.....",
        ".###....",
        ".####...",
        ".###....",
        ".##.....",
        ".#......",
        "........",
    ],
    # font-metric slash and dash (fujidisp's UDC art)
    "SLASH": [
        "......#.",
        ".....#..",
        "....#...",
        "...#....",
        "..#.....",
        ".#......",
        "........",
        "........",
    ],
    "DASH": [
        "........",
        "........",
        "........",
        ".#####..",
        "........",
        "........",
        "........",
        "........",
    ],
    "BLANK": ["........"] * 8,
}

BANKS = [
    ("UDCBT", "bank T: title + game",
     ["HEART", "DIAMOND", "CLUB", "SPADE", "TEN", "CHIP", "BACK", "CHEVR"]),
    ("UDCBL", "bank L: lobby + name entry",
     ["CHEVR", "SLASH", "DASH", "BLANK", "BLANK", "BLANK", "BLANK", "BLANK"]),
]


def rowbyte(row: str) -> int:
    assert len(row) == 8, row
    v = 0
    for i, ch in enumerate(row):
        assert ch in "#.", row
        if ch == "#":
            v |= 0x80 >> i
    return v


def main() -> None:
    for name, art in GLYPHS.items():
        assert len(art) == 8, name

    lines = [
        "; udc.inc -- generated by tools/mkudc.py; do not edit.",
        ";",
        "; Two 64-byte UDC banks for $1980-$19BF (glyph codes $38-$3F; the",
        "; first four slots are also the sprite images). Reloaded per screen",
        "; by UDLDT/UDLDL below (page-1 code: the data is in block 2, the",
        "; UDC RAM is page 0, so the copy runs through the PUDC pointer).",
        "",
    ]
    total = 0
    for label, desc, names in BANKS:
        lines.append(f"; ---- {desc} " + "-" * max(0, 55 - len(desc)))
        lines.append(f"{label}:")
        for slot, name in enumerate(names):
            art = GLYPHS[name]
            lines.append(f"; ${0x38 + slot:02X} {name}")
            for row in art:
                b = rowbyte(row)
                lines.append(f"        DB      %{b:08b}        ; {row}")
                total += 1
        lines.append("")

    loader = """\
; UDLDT / UDLDL: load a bank into the UDC RAM. Page-1 code; clobbers R0,R3.
UDLDT:  LODI,R3 63
UDLT1:  LODA,R0 UDCBT,R3
        STRA,R0 *PUDC,R3
        BDRR,R3 UDLT1
        LODA,R0 UDCBT
        STRA,R0 *PUDC
        RETC,UN

UDLDL:  LODI,R3 63
UDLL1:  LODA,R0 UDCBL,R3
        STRA,R0 *PUDC,R3
        BDRR,R3 UDLL1
        LODA,R0 UDCBL
        STRA,R0 *PUDC
        RETC,UN

PUDC:   DWBE    UDC
"""
    lines.append(loader)

    assert total == 128, total
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({total} data bytes, 2 banks)")


if __name__ == "__main__":
    sys.exit(main())
